Equations

QXCAPNTC(T,RRR,RRR)              'Transmission (NTC-based) plus transmission capacity reserved for providing secondary reserve lower than capacities'
QXCAPDC(T,RRR,RRR)               'Transmission (RAM-based via DC-lines in Flow-Based MC-Region) plus transmission capacity reserved for providing secondary reserve lower than capacities'

QXCAPFBMCPlus(T,FLG)             'New Transmission limit under PTDF in positive direction both (for day-ahead market)'
QXCAPFBMCMinus(T,FLG)            'New Transmission limit under PTDF in negative direction both (for day-ahead market)'

;


