Equations
QXCAP(T,RRR,RRR)          'Transmission plus transmission capacity reserved for providing secondary reserve lower than capacities'     
QXCAPDAYAHEAD (T,RRR,RRR) 'Transmission on day-ahead market lower than capacities'     
QXKPTDF5Plus(T,RRR,RRR)   'Transmission limit under PTDF in positive direction both'
QXKPTDF5Minus(T,RRR,RRR)  'Transmission limit under PTDF in negative direction both'
;  